### PR TITLE
Tweaks to changelog in advance of release.

### PR DESCRIPTION
**Pull request by gtcampbell**
Any wordsmithing and/or callouts of missing information would be
appreciated.

### CODE REVIEW

**Comment by klingerf** [comment]
Maybe put the bullet about namerd at the top, with special emoji? It's pretty special after all.

**Comment by adleong** [comment]
:star: :sparkles:

**Comment by olix0r** [comment]
:star: :sparkles:

**Comment by klingerf** [comment]
:star: Great, thanks for updating.

**Pull request merged**
