### PR TITLE
Add context links to docs

### LINKED ISSUE #451: add more context to split config file docs
Now that we've split config into sections with 0.6.0, the individual "split" pages are missing some context.

E.g. https://linkerd.io/doc/0.6.0/linkerd/retries/ doesn't mention that the block itself is called `retries`, or that it belongs in the `client` section. You need to navigate to another page to get to that.

At a minimum, we should add the above two bits of information to each of the split pages.

### PR DESCRIPTION
**Pull request by adleong**
Fixes #451

### CODE REVIEW

**Comment by esbie** [comment]
⭐ 
tioli: a wordier intro, eg "This documentation section describes the configuration options for the loadbalancer key"

**Comment by olix0r** [comment]
lgtm.

I think it would be even clearer to include a full snippet of how each of these is used in the context of a configuration file.  E.g. for tls:

```yaml
routers:
- ...
  client:
    tls:
      kind: io.l5d.static
      commonName: foo.example.com
```

**Comment by gtcampbell** [comment]
:star: LGTM

**Comment by olix0r** [comment]
:star:

**Pull request merged**
