### PR TITLE
Namerd with etcd storage on non-default port fails

### PR DESCRIPTION
**Pull request by OleksandrBerezianskyi**
Fix for the issue #689

### CODE REVIEW

**Comment by adleong** [comment]
:star: good catch! Thanks, @OleksandrBerezianskyi

**Comment by adleong** [comment]
Could you please sign our CLA? https://buoyant.io/cla/

**Comment by OleksandrBerezianskyi** [comment]
@adleong - just signed

**Comment by adleong** [comment]
Thanks!!!

**Pull request merged**
