### PR TITLE
Fix a couple of typos

### PR DESCRIPTION
**Pull request by topiaruss**

### CODE REVIEW

**Comment by adleong** [comment]
:star: Good catch!  Thanks for fixing, @topiaruss.

**Comment by olix0r** [comment]
:shipit: thanks @topiaruss!

**Comment by adleong** [comment]
We'll actually need you to sign the CLA, @topiaruss, even for doc fixes.  https://buoyant.io/cla/  

Sorry for the trouble and thanks for the fix!

**Comment by topiaruss** [comment]
Done.
NP.
—r
> On 2 May 2016, at 21:02, Alex Leong <notifications@github.com> wrote:
> 
> We'll actually need you to sign the CLA, @topiaruss <https://github.com/topiaruss>, even for doc fixes. https://buoyant.io/cla/ <https://buoyant.io/cla/>
> Sorry for the trouble and thanks for the fix!
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub <https://github.com/BuoyantIO/linkerd/pull/359#issuecomment-216346143>

Russ Ferriday -- Software Product Architect, Developer, Mentor
Founder & CTO Topia Systems Ltd.
russf@topia.com  --  +44 7429 518822

**Pull request merged**
