### PR TITLE
Improve admin and Namerd initialization

### PR DESCRIPTION
**Pull request by olix0r**
Admin server initialization is far too verbose. Tidy up admin server
initialization, reducing log level on admin endpoint logging.

### CODE REVIEW

**Comment by olix0r** [comment]
based on #651.

**Comment by adleong** [comment]
What's the net effect here?

* Endpoint list at startup moved from INFO to DEBUG level
* Exceptions during admin initialization no longer print stack traces?
* Slight refactor without any change of behavior
* Anything else?

**Comment by olix0r** [comment]
- Endpoint list at startup moved from INFO to DEBUG
- the admin server Monitor still prints stack traces but uses the logger instead of our own version of stacktrace printing.
- AdminInitializer is just a function instead of a mutable/stateful class
- Namerd shutdown ordering is fixed.

**Comment by adleong** [comment]
:star: 🔇

**Comment by olix0r** [comment]
:star: doubleship?

**Pull request merged**
