### PR TITLE
Update examples to add explicit server ports.

### LINKED ISSUE #134: Update examples to reflect removal of default ports
Along with global router params, we no longer support default server ports in configuration, but there are still some examples making use of them.

### PR DESCRIPTION
**Pull request by gtcampbell**
Fixes #134.

### CODE REVIEW

**Comment by olix0r** [comment]
Would you mind updating config.md as well?  We mention default ports several times in that doc.

**Comment by adleong** [comment]
The config refactor made the servers section mandatory but protocols still define default ports.  We should either keep the default port stuff in the docs, or remove it from the code.

**Comment by gtcampbell** [comment]
we will revisit the default port stuff for the next release.

**Comment by olix0r** [comment]
:star: after rebase

**Comment by rmars** [comment]
:+1:

**Pull request merged**
