### PR TITLE
Add CHANGES.md, drop release- prefixes

### PR DESCRIPTION
**Pull request by klingerf**
Going forward, we're going to track changes to linkerd directly in this repo, in CHANGES.md.  We're also dropping the "release-" prefix that shows up in our tag names on the Github releases page.

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/BuoyantIO/linkerd/pull/107" target="_blank">ReviewNinja

**Comment by siggy** [comment]
:+1: :star:

**Comment by rmars** [comment]
:star:

**Comment by olix0r** [comment]
I think I'd prefer that we wrap CHANGES.md at 80 or 100 chars...  not a real blocker :+1:

**Comment by klingerf** [comment]
@olix0r Good suggestion -- have added wrapping as part of this branch.

**Pull request merged**
