### PR TITLE
Update dtabs to use globs

### PR DESCRIPTION
**Pull request by olix0r**
Remove uses of io.buoyant.http.any* namers in favor of finagle's new wildcard support.

### CODE REVIEW

**Comment by adleong** [comment]
:star: 🎉 📇

**Comment by klingerf** [comment]
I want to test part of this change on the kubernetes demo -- mind hold off on shipping for a few mins?

**Comment by rmars** [comment]
:star: 👣

**Comment by klingerf** [comment]
⭐ 🔧 

i_like_it_a_lot

**Pull request merged**
