### PR TITLE
Add telemetryCore to all in LinkerdBuild

### PR DESCRIPTION
**Pull request by Ashald**
Otherwise it's missing when, for example, `./sbt publishLocal` is executed.

Spotted on Friday thanks to @adleong.

### CODE REVIEW

**Comment by olix0r** [comment]
:star: will merge after CI passes

**Comment by olix0r** [comment]
It looks like this uncovers an actual test error.  Would you mind fixing the test (missing _T_)?

```
com.fasterxml.jackson.databind.JsonMappingException: Could not resolve type id 'io.l5d.testelemeter' into a subtype of [simple type, class io.buoyant.telemetry.TelemeterConfig]: known type ids = [TelemeterConfig, io.l5d.testTelemeter]
```

**Comment by Ashald** [comment]
Sure

**Comment by olix0r** [comment]
thanks!

**Comment by Ashald** [comment]
You're welcome ;)

**Pull request merged**
