### PR TITLE
Switching to medallia headers

### PR DESCRIPTION
**Pull request by AbhiMedallia**
Tested locally by forwarding to my own web server and making sure the right headers were being forwarded.

### CODE REVIEW

**Comment by olix0r** [comment]
Thanks for the patch, @AbhiMedallia!  This is really cool.

I don't think we should add Medallia-specific logic to linkerd; but I understand the need to support an alternate header scheme.  This seems like a good target for a new plugin subsystem, so that you can maintain this outside of the linkerd repo.  If we could provide such a plugin interface, would that work for you?

**Comment by erdody** [comment]
@olix0r sorry, this was meant to be merged to our fork's branch. 
Having a plugin system would be great. 
Thanks!

**Comment by abhinigam** [comment]
My bad.

**Comment by olix0r** [comment]
No worries. If you let us know (via Issues is best) of the places where you have found the need to modify linkerd, I think we'd be pretty interested in getting plugin interfaces in place so that you can maintain separate packages instead of a substantial fork.  Looks like you're making good progress, though ;)

**Comment by AbhiMedallia** [comment]
Hi Oliver,
Sorry about that. I am just figuring out the github stuff and did not
realize I was sending the diff to you guys.
These are medallia specific changes. As far as I am concerned the headers
work pretty well as they are. This is just for policy/aesthetic reasons why
we are changing the header names.

-Abhishek

**Comment by olix0r** [comment]
@AbhiMedallia no problem. If you've found the need to change this sort of thing, I expect other users will as well. Ideally, you should be able to run vanilla-released linkerd with a set of medallia specific plugins (provided at runtime) to get all of the features you need.  This should substantially reduce your maintenance overhead in the long run.

**Comment by AbhiMedallia** [comment]
Hi Oliver,
If I want to contribute this kafka telemeter patch back to buoyant linkerd
master how should I proceed.
I think this patch will be really useful for others considering kafka as
the transport protocol for tracing.

-Abhishek

**Comment by AbhiMedallia** [comment]
Here is what the config looks like:

telemetry:

- kind: io.l5d.kafkazipkin

  sampleRate: 1

  brokerList: 192.168.99.100:9092

  numRetries: 10


I am attaching the patch to this email thread itself to make it easier for
someone to use.


-Abhishek

**Comment by wmorgan** [comment]
Hi Abhishek,

Awesome, I would love to have this feature! If you have it on a branch, you can make a Github pull request against BuoyantIO/linkerd... that is the starting point for getting it into the main distro.

**Comment by AbhiMedallia** [comment]
Hi William,
I have the changes on a branch called KafkaTelemeter but I do not have
permissions to push these changes to remote branch on github.

anigam-mbp:linkerd anigam$ git push origin KafkaTelemeter

remote: Permission to BuoyantIO/linkerd.git denied to AbhiMedallia.

fatal: unable to access 'https://github.com/BuoyantIO/linkerd.git/': The
requested URL returned error: 403
-Abhishek

**Comment by klingerf** [comment]
Hi Abhi,

In order to create a pull request, you can push your branch to a fork of
the linkerd repo, rather than pushing directly to BuoyantIO's linkerd
repo.  You can fork the repo by clicking the fork button in the Github UI.
This document describes the fork / pull request workflow pretty thoroughly:

https://gist.github.com/Chaser324/ce0505fbed06b947d962

Hopefully that's helpful, but let us know if you get stuck.

Kevin

**Comment by AbhiMedallia** [comment]
I have created a pull request:https://github.com/BuoyantIO/linkerd/pull/796
Thanks for the guidance.
https://github.com/BuoyantIO/linkerd/pull/796

yaml looks like:

telemetry:

- kind: io.l5d.kafkazipkin

  sampleRate: 1

  brokerList: 192.168.99.100:9092

  numRetries: 10

-Abhishek

**Pull request closed without merging**
