### PR TITLE
Clean up value-discarded warnings in namerd-storage-zk.

### PR DESCRIPTION
**Pull request by adleong**

### CODE REVIEW

**Comment by klingerf** [comment]
⭐ 🐢

**Comment by olix0r** [comment]
Can you provide a brief description of what behavior is changing (i.e. in the commit message)?

**Comment by olix0r** [comment]
Oh.. what is a "value discarded warning" is this some intellij thing? (turn that off?)

**Comment by olix0r** [comment]
:star: After discussion, I'm good with this -- this will help catch subtle errors.  We'll get used to reading `val _ = `

**Pull request merged**
